/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  Person,
} from './components/person/person.interface';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppAvatar {
    'name': string;
    'points': number;
  }
  interface AppAvatarAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'points'?: number;
  }

  interface AppHistoryList {
    'name': string;
  }
  interface AppHistoryListAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppPerson {
    'name': string;
    'person': Person;
    'points': number;
    'rank': number;
  }
  interface AppPersonAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'person'?: Person;
    'points'?: number;
    'rank'?: number;
  }

  interface AppRankings {
    'name': string;
  }
  interface AppRankingsAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppAvatar': Components.AppAvatar;
    'AppHistoryList': Components.AppHistoryList;
    'AppPerson': Components.AppPerson;
    'AppRankings': Components.AppRankings;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-avatar': Components.AppAvatarAttributes;
    'app-history-list': Components.AppHistoryListAttributes;
    'app-person': Components.AppPersonAttributes;
    'app-rankings': Components.AppRankingsAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppAvatarElement extends Components.AppAvatar, HTMLStencilElement {}
  var HTMLAppAvatarElement: {
    prototype: HTMLAppAvatarElement;
    new (): HTMLAppAvatarElement;
  };

  interface HTMLAppHistoryListElement extends Components.AppHistoryList, HTMLStencilElement {}
  var HTMLAppHistoryListElement: {
    prototype: HTMLAppHistoryListElement;
    new (): HTMLAppHistoryListElement;
  };

  interface HTMLAppPersonElement extends Components.AppPerson, HTMLStencilElement {}
  var HTMLAppPersonElement: {
    prototype: HTMLAppPersonElement;
    new (): HTMLAppPersonElement;
  };

  interface HTMLAppRankingsElement extends Components.AppRankings, HTMLStencilElement {}
  var HTMLAppRankingsElement: {
    prototype: HTMLAppRankingsElement;
    new (): HTMLAppRankingsElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-avatar': HTMLAppAvatarElement
    'app-history-list': HTMLAppHistoryListElement
    'app-person': HTMLAppPersonElement
    'app-rankings': HTMLAppRankingsElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-avatar': HTMLAppAvatarElement;
    'app-history-list': HTMLAppHistoryListElement;
    'app-person': HTMLAppPersonElement;
    'app-rankings': HTMLAppRankingsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
