/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppAvatar {
    'name': string;
    'points': number;
  }
  interface AppAvatarAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'points'?: number;
  }

  interface AppHistoryList {
    'name': string;
  }
  interface AppHistoryListAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppPersonList {
    'name': string;
  }
  interface AppPersonListAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppPerson {
    'name': string;
    'points': number;
    'user': string;
  }
  interface AppPersonAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'points'?: number;
    'user'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppAvatar': Components.AppAvatar;
    'AppHistoryList': Components.AppHistoryList;
    'AppPersonList': Components.AppPersonList;
    'AppPerson': Components.AppPerson;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-avatar': Components.AppAvatarAttributes;
    'app-history-list': Components.AppHistoryListAttributes;
    'app-person-list': Components.AppPersonListAttributes;
    'app-person': Components.AppPersonAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppAvatarElement extends Components.AppAvatar, HTMLStencilElement {}
  var HTMLAppAvatarElement: {
    prototype: HTMLAppAvatarElement;
    new (): HTMLAppAvatarElement;
  };

  interface HTMLAppHistoryListElement extends Components.AppHistoryList, HTMLStencilElement {}
  var HTMLAppHistoryListElement: {
    prototype: HTMLAppHistoryListElement;
    new (): HTMLAppHistoryListElement;
  };

  interface HTMLAppPersonListElement extends Components.AppPersonList, HTMLStencilElement {}
  var HTMLAppPersonListElement: {
    prototype: HTMLAppPersonListElement;
    new (): HTMLAppPersonListElement;
  };

  interface HTMLAppPersonElement extends Components.AppPerson, HTMLStencilElement {}
  var HTMLAppPersonElement: {
    prototype: HTMLAppPersonElement;
    new (): HTMLAppPersonElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-avatar': HTMLAppAvatarElement
    'app-history-list': HTMLAppHistoryListElement
    'app-person-list': HTMLAppPersonListElement
    'app-person': HTMLAppPersonElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-avatar': HTMLAppAvatarElement;
    'app-history-list': HTMLAppHistoryListElement;
    'app-person-list': HTMLAppPersonListElement;
    'app-person': HTMLAppPersonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
